import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const OWNER = "edwin.vega@gmail.com";
const ADDED = new Date("2026-05-01T00:00:00Z");

const items = [
  {
    id: "0a3b9523-b9be-4778-8788-5a5a0f49e11f",
    ownerEmail: OWNER,
    title: "OpenClaw vs. Hermes Agent: The race to build AI assistants that never forget",
    url: "https://thenewstack.io/persistent-ai-agents-compared/",
    summary: "Janakiram MSV in The New Stack compares two open-source persistent AI coding agents that aim to fix the context-loss problem of session-based tools like Claude Code, Codex, and Cursor. OpenClaw and Hermes Agent represent a new software category — always-on agents that live on your infrastructure, remember what they learned last month, and improve over time. The piece argues the AI agent landscape is splitting into session-bound tools versus permanent agent runtimes, with OpenClaw prioritizing ecosystem reach and Hermes Agent prioritizing deep learning over time.",
    category: "ai",
    subcategory: "news",
    tags: ["openclaw", "hermes-agent", "persistent-agents", "the-new-stack", "agent-runtime"],
    source: "manual",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "37001463-539b-4899-b628-01c8f7d0983c",
    ownerEmail: OWNER,
    title: "GitNexus — Knowledge graph engine for codebases",
    url: "https://github.com/abhigyanpatwari/GitNexus",
    summary: "Client-side knowledge graph engine that indexes codebases so AI agents understand structure deeply. Analyzes dependencies, call chains, and execution flows to prevent breaking changes. Ships with a Graph RAG agent, a multi-repo MCP server with 16 tools (impact analysis, process-grouped search, multi-file rename) for Cursor/Claude Code/Codex/Windsurf, plus a server-less browser web UI. Supports 14+ languages. 34.1k stars, TypeScript, PolyForm Noncommercial.",
    category: "ai",
    subcategory: "tool",
    tags: ["knowledge-graph", "mcp", "graph-rag", "code-indexing", "open-source"],
    source: "manual",
    read: false,
    color: "blue",
    dateAdded: ADDED,
  },
  {
    id: "ce054dd2-7720-4024-9f11-97a4cec149c0",
    ownerEmail: OWNER,
    title: "Trinity-Large open source supera a Claude Opus y GPT-5.4 en OpenClaw",
    url: "https://www.facebook.com/61578950499375/posts/122155955438965016/",
    summary: "Post de Prompt Models Studio: el modelo open source Trinity-Large encabeza el ranking de OpenClaw con 91.9%, por encima de Claude Opus (83.1%) y GPT-5.4 (81.7%). Disponible gratis en OpenRouter como `arcee-ai/trinity-large-preview:free`. En los comentarios Oscar Olvera explica que es un modelo MoE de 400B parámetros (13B activos en inferencia, 1024 expertos), entrenado en California por $20M durante 33 días en 1024 GPUs, ideal como alternativa barata a Claude para iterar.",
    category: "ai",
    subcategory: "model",
    tags: ["trinity-large", "openrouter", "arcee-ai", "open-source", "benchmarks"],
    source: "facebook",
    read: false,
    color: "amber",
    content: "**Ranking en OpenClaw:**\n- Trinity-Large — 91.9%\n- Claude Opus — 83.1%\n- GPT-5.4 — 81.7%\n\n**Cómo usarlo:** OpenRouter → `arcee-ai/trinity-large-preview:free`\n\n**Detalles técnicos** (vía Oscar Olvera en los comentarios):\n- 400B parámetros totales, 13B activos por inferencia\n- Mezcla de Expertos: 1024 expertos (uno por GPU durante entrenamiento)\n- Entrenado por $20M en 33 días sobre 1024 GPUs\n- Desarrollado en California\n- Útil como alternativa a Claude para probar e iterar antes de pasar a Claude Code",
    dateAdded: ADDED,
  },
  {
    id: "8067ea47-93b8-4fc7-8a99-9d3ac5ca75ad",
    ownerEmail: OWNER,
    title: "I had Claude read every harness engineering guide and build me one",
    url: "https://www.reddit.com/r/ClaudeAI/comments/1s9jm0d/i_had_claude_read_every_harness_engineering_guide/",
    summary: "r/ClaudeAI post by celesteanders: synthesizes four harness-engineering guides (two from Anthropic, OpenAI's Codex piece, and Geoffrey Huntley's 'Ralph Wiggum as a Software Engineer') into a single best-practices.md, then has Claude build a minimal harness from it. Key principles surfaced across all sources: separate generation from evaluation, structured files (JSON task lists, progress notes, git history) over context windows, one task per session, baseline check at session start, and strip harness complexity with each model upgrade.",
    category: "ai",
    subcategory: "tutorial",
    tags: ["harness-engineering", "claude-code", "agents", "best-practices", "reddit"],
    source: "reddit",
    read: false,
    color: "blue",
    content: "**Source articles synthesized:**\n- [Harness Design for Long-Running Apps](https://www.anthropic.com/engineering/harness-design-long-running-apps) — Anthropic\n- [Effective Harnesses for Long-Running Agents](https://www.anthropic.com/engineering/effective-harnesses-for-long-running-agents) — Anthropic\n- [Harness Engineering: Leveraging Codex in an Agent-First World](https://openai.com/index/harness-engineering/) — OpenAI\n- [Ralph Wiggum as a Software Engineer](https://ghuntley.com/ralph/) — Geoffrey Huntley\n\n**Cross-source principles:**\n1. Separate generation from evaluation — agents are bad at grading themselves\n2. Context windows are the constraint; structured files (JSON task lists, progress notes, git) are the solution\n3. One task per session\n4. Verify before building — baseline check at session start\n5. Strip harness complexity with each model upgrade",
    dateAdded: ADDED,
  },
  {
    id: "33998efe-b094-4eab-825d-875bce297f56",
    ownerEmail: OWNER,
    title: "Claude Code command cheat sheet — control surface for workflow management",
    url: "https://www.facebook.com/groups/claudeaicommunity/permalink/1253493756817789/",
    summary: "Post de AI HubSeek en el grupo Claude Ai Community: una hoja de referencia que mapea cada comando de Claude Code y cómo usarlos para estructurar workflows, gestionar archivos e iterar de idea a código sin fricción. El argumento: la mayoría de usuarios no aprovechan la capa de comandos, y ese vacío explica por qué sus builds se vuelven lentos y fragmentados.",
    category: "ai",
    subcategory: "tutorial",
    tags: ["claude-code", "cheat-sheet", "commands", "workflow", "ai-hubseek"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "b5e5da9a-93fc-4582-b494-cc7b72108198",
    ownerEmail: OWNER,
    title: "Claude ahora busca y te consigue clientes — Soy Enrique Rocha (reel)",
    url: "https://www.facebook.com/reel/1676207793382999",
    summary: "Reel de Soy Enrique Rocha mostrando cómo usar Claude para prospectar y conseguir clientes nuevos automáticamente. Demuestra un flujo donde Claude busca prospectos y prepara el outreach. Audio original del autor; 4.2K reacciones, 1.1K comentarios.",
    category: "ai",
    subcategory: "tool",
    tags: ["claude", "prospeccion", "ventas", "enrique-rocha", "espanol"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "90026d25-aec3-4ef1-843b-ac591bffbcc1",
    ownerEmail: OWNER,
    title: "NVIDIA gives free API access to 80+ top-tier AI models",
    url: "https://www.facebook.com/61579900588732/posts/122137579748996686/",
    summary: "Alex AI Update post: NVIDIA quietly offers free API access to 80+ models (MiniMax, GLM, Kimi, DeepSeek, GPT-OSS, etc.) through an OpenAI-compatible endpoint at integrate.api.nvidia.com/v1. Drop-in replacement for Cursor, Zed, OpenClaw or any agent framework — no infra changes needed. Three-step setup: get an API key at build.nvidia.com/models, set base_url, pick a model. Generous free-tier for prototyping without GPU clusters.",
    category: "ai",
    subcategory: "tool",
    tags: ["nvidia", "free-api", "openai-compatible", "nim", "models"],
    source: "facebook",
    read: false,
    color: "amber",
    content: "**Setup (3 steps):**\n1. Grab API key → build.nvidia.com/models\n2. Update base_url → `integrate.api.nvidia.com/v1`\n3. Add key + select target model\n\n**Models available:** MiniMax, GLM, Kimi, DeepSeek, GPT-OSS, and 80+ others.\n\n**Compatible with:** Cursor, Zed, OpenClaw, any OpenAI-compatible agent framework.\n\nFree-tier limit aimed at indie hackers prototyping without burning cash on GPU clusters.",
    dateAdded: ADDED,
  },
  {
    id: "fd04473b-4265-439a-8d80-e9859aed016c",
    ownerEmail: OWNER,
    title: "free-claude-code — Proxy for routing Claude Code to alternative providers",
    url: "https://github.com/Alishahryar1/free-claude-code",
    summary: "Drop-in proxy server that routes Claude Code API calls to alternative AI providers instead of Anthropic. Supports six backends (NVIDIA NIM, OpenRouter, DeepSeek, LM Studio, llama.cpp, Ollama) with per-model routing for Opus/Sonnet/Haiku tiers. Maintains streaming, tool use, and thinking-block compatibility, plus an optional Discord/Telegram bot wrapper with voice transcription. Lets you run Claude Code free or cheap via OpenRouter free tiers or local models. 19.7k stars, MIT.",
    category: "ai",
    subcategory: "tool",
    tags: ["claude-code", "proxy", "openrouter", "ollama", "open-source"],
    source: "manual",
    read: false,
    color: "blue",
    dateAdded: ADDED,
  },
  {
    id: "fb2036f2-10d1-4cdb-953d-055895a9c761",
    ownerEmail: OWNER,
    title: "100x Engineers — Deep dive teaser (reel)",
    url: "https://www.facebook.com/reel/26487202187639953",
    summary: "Reel promocional de 100x Engineers invitando a comentar 'Deep' para acceder a un evento o cohorte ese fin de semana. Cuenta de educación en ingeniería y AI orientada a developers que quieren operar al nivel de '100x'. Sin contenido sustantivo público en el reel, solo CTA.",
    category: "ai",
    subcategory: "tutorial",
    tags: ["100x-engineers", "cohort", "education", "reel"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "54e2fd88-445d-4e23-ba7b-77e1542cd8d9",
    ownerEmail: OWNER,
    title: "What Agentic RAG actually looks like — 6-step blueprint",
    url: "https://www.facebook.com/100064955110716/posts/1358384576336700/",
    summary: "AI MATT explica Agentic RAG en 6 pasos: el usuario pregunta, un Aggregator Agent recibe la query y consulta Memory + Planning, despacha sub-agentes (archivos locales, búsqueda web, cloud) vía MCP, agrega los resultados y los pasa al modelo generativo (GPT/Claude/Gemini), que devuelve una respuesta única, fundamentada en datos reales. Define cuatro etapas de adopción: Stage 1 (ChatGPT manual) → Stage 2 (Zapier/Make) → Stage 3 (agentes con tools) → Stage 4 (diseñas estos sistemas para terceros).",
    category: "ai",
    subcategory: "tutorial",
    tags: ["agentic-rag", "mcp", "rag", "ai-matt", "blueprint"],
    source: "facebook",
    read: false,
    color: "blue",
    content: "**6-step Agentic RAG blueprint:**\n1. User asks a question\n2. Aggregator Agent (project manager) picks up the query\n3. Checks Memory (past context) + Planning (breaks job into steps)\n4. Dispatches sub-agents via MCP servers:\n   - Agent 1 — local files, databases, PDFs\n   - Agent 2 — live web search\n   - Agent 3 — cloud platforms (AWS, Azure)\n5. Aggregator collects all fetched info + original query + extra context → sends to generative model (GPT/Claude/Gemini)\n6. Model returns a single grounded answer\n\n**Adoption stages:**\n- Stage 1 — ChatGPT/Claude one question at a time\n- Stage 2 — Zapier/Make automations (disconnected)\n- Stage 3 — Agents with tools that coordinate\n- Stage 4 — Designing these systems for clients",
    dateAdded: ADDED,
  },
  {
    id: "73ab04e8-01af-4481-a8cd-480e5de449bc",
    ownerEmail: OWNER,
    title: "Uptime Kuma — Self-hosted uptime monitoring",
    url: "https://github.com/louislam/uptime-kuma",
    summary: "Self-hosted monitoring tool that tracks availability of HTTP(s), TCP, DNS, WebSocket, Ping, and Docker containers with 20-second check intervals. Modern reactive UI, 90+ notification integrations (Telegram/Discord/Slack/Email), multiple status pages with custom domains, 2FA, ping charts, and SSL cert tracking. The de-facto self-hosted alternative to UptimeRobot. 86.1k stars, MIT.",
    category: "bookmarks",
    subcategory: "site",
    tags: ["self-hosted", "monitoring", "uptime", "open-source", "docker"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "a7821a8e-679b-4287-8d3a-bc2ad62eb2f5",
    ownerEmail: OWNER,
    title: "Claude Code Operating System V2 — Repository as execution system",
    url: "https://www.facebook.com/61579900588732/posts/122137846148996686/",
    summary: "Alex AI Update argues prompts are just the interface — repository structure is the real intelligence. Maps a Claude project as 8 intentional layers: CLAUDE.md (system brain — mission, mental model, execution rules), .claude/memory/ (long-term intelligence), .claude/skills/ (reusable capabilities), .claude/agents/ (architect/coder/reviewer/optimizer roles), .claude/workflows/ (plan→build→review→test→ship automation), .claude/hooks/ (enforcement), docs/ (source of truth via ADRs/runbooks), and local CLAUDE.md (precedence overrides).",
    category: "ai",
    subcategory: "tutorial",
    tags: ["claude-code", "system-design", "repository-structure", "agents", "skills"],
    source: "facebook",
    read: false,
    color: "blue",
    content: "**8 layers of a Claude Code project:**\n1. **CLAUDE.md** — System brain. Mission, mental model, execution rules. Keep it short — clarity > completeness.\n2. **.claude/memory/** — Long-term intelligence. Patterns that worked, repeated mistakes, learnings.\n3. **.claude/skills/** — Reusable execution units (code review, debugging, refactoring, release).\n4. **.claude/agents/** — Division of thinking: architect, coder, reviewer, optimizer.\n5. **.claude/workflows/** — Automation: plan → build → review → test → ship.\n6. **.claude/hooks/** — Enforcement (formatting, tests, restricted areas).\n7. **docs/** — Source of truth: architecture, ADRs, runbooks. Designed for navigation, not memorization.\n8. **Local CLAUDE.md** — Precedence overrides (cut off in source).",
    dateAdded: ADDED,
  },
  {
    id: "c835f3a1-2800-4934-a375-7f3b0e23ec0d",
    ownerEmail: OWNER,
    title: "Magic Resume — Real-time web resume builder with themes and animations",
    url: "https://github.com/JOYCEQL/magic-resume",
    summary: "Modern web-based resume builder with real-time editing and instant preview, smooth Framer Motion animations, and customizable themes. Dark mode, responsive, PDF export, auto-save to local storage. Built on TanStack Start. 7.3k stars, Apache 2.0 (commercial use requires paid license).",
    category: "bookmarks",
    subcategory: "site",
    tags: ["resume", "cv-builder", "tanstack", "framer-motion", "open-source"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "f460fdc0-ed2d-422e-9589-474e7a223a21",
    ownerEmail: OWNER,
    title: "hackingtool — All-in-one security framework with 185+ pentest tools",
    url: "https://github.com/Z4nzu/hackingtool",
    summary: "All-in-one security framework aggregating 185+ penetration testing and reconnaissance tools behind a unified menu-driven Python CLI. 20 categories: OSINT, web attacks, wireless security, reverse engineering, cloud/AD assessment, exploit frameworks, post-exploitation. Interactive search, tag filtering, install status indicators, batch install. Cross-platform (Linux/Kali/ParrotOS/macOS) with Docker. 69.8k stars, MIT.",
    category: "bookmarks",
    subcategory: "site",
    tags: ["pentest", "security", "osint", "kali", "open-source"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "dfaad0a0-a0fe-42bc-88ab-f2028c04451c",
    ownerEmail: OWNER,
    title: "Certified Master in Agentic AI — 52-Week Applied Program (Udemy)",
    url: "https://www.udemy.com/course/certified-master-in-agentic-ai/",
    summary: "Hands-on Udemy program covering Agentic AI, multi-agent systems, and LLMs across 52 weeks and 156 expert-led topics. Walks through agent anatomy (LLMs, memory, tools, goals), then frameworks (LangChain, LangGraph, CrewAI, AutoGPT, BabyAGI, LlamaIndex), vector DBs (FAISS/Pinecone/Chroma), cloud integration (AWS/Azure/GCP), workflow tools (n8n/Zapier), observability (Prometheus/Grafana/OTel), AI safety/guardrails/HITL/governance. Final quarter focuses on autonomous agents and swarm intelligence. Includes domain-specific labs (finance, healthcare, law, education, robotics).",
    category: "ai",
    subcategory: "course",
    tags: ["agentic-ai", "udemy", "langchain", "crewai", "multi-agent"],
    source: "manual",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "c007a8e4-5eda-4c79-ba86-45f56ea1c2f0",
    ownerEmail: OWNER,
    title: "Premise — Thoughts on planning in the agentic era",
    url: "https://kdemoya.github.io/premise/",
    summary: "Kelvin De Moya argues that with code generation now automated, the expensive work has shifted from typing to judgment — but agile tooling was optimized for measuring typing effort. He proposes replacing sprint-based ticket systems with a two-level structure: initiatives (outcome commitments) and specs (flexible execution units), plus decision logs that preserve organizational thinking. Premise is the open-source reference implementation. Teams should commit to outcomes rather than fixed ticket baskets, and readiness should be a visible, checkable state.",
    category: "ai",
    subcategory: "research",
    tags: ["agentic-planning", "agile", "decision-logs", "kelvin-demoya", "premise"],
    source: "manual",
    read: false,
    color: "blue",
    dateAdded: ADDED,
  },
  {
    id: "08e73354-289b-4713-bf13-23a20125edbc",
    ownerEmail: OWNER,
    title: "Claude + Codex + Opencode = God Mode (multi-lineage reviewer setup)",
    url: "https://www.reddit.com/r/ClaudeCode/comments/1sxs8c0/claude_codex_opencode_god_mode/",
    summary: "r/ClaudeCode post by 99xAgency describing a multi-agent dev setup running in tmux: 3x Codex CLI on separate ChatGPT Plus accounts, Gemini 3.1 Pro, Kimi K2.6 + DeepSeek V4 Pro via OpenCode Go. A custom /work command builds context packs and dispatches to 3 reviewers in parallel for plan/implement/major-bug/minor-bug shapes. Key insight: 'lineage diversity' — pick one Codex + one Gemini + one OpenCode, since same-family models share blind spots. Claude must get all three lineages to agree (consensus gate) before merge, with a 4-question checklist (coding principles, architecture drift, tests pass, reviewer consensus).",
    category: "ai",
    subcategory: "tutorial",
    tags: ["multi-agent", "claude-code", "codex", "opencode", "lineage-diversity"],
    source: "reddit",
    read: false,
    color: "blue",
    content: "**Stack (all in tmux):**\n- 3× Codex CLI (separate ChatGPT Plus accounts so reset windows don't collide)\n- Gemini 3.1 Pro Preview\n- Kimi K2.6 + DeepSeek V4 Pro via OpenCode Go (cheaper than API, 3× limits on Kimi)\n\n**`/work` command shapes:** plan, implement, major bug, minor bug. Builds a context pack, dispatches to 3 reviewers in parallel, waits for consensus.\n\n**Lineage diversity rule:** reviewers = 1 Codex + 1 Gemini + 1 OpenCode. Same-family = echo chamber. All three lineages must agree → gate opens. Otherwise Claude revises and re-runs.\n\n**Pre-merge 4-Q checklist:**\n1. Coding principles\n2. Architecture drift\n3. Tests pass\n4. Reviewer consensus\n→ pick merge / fix first / override with reason.\n\n**Cost:** ~$0 on top of existing subscriptions.\n\n**Why it works:** Opus failures are silent — code looks reasonable, tests pass, but subtle bugs/design drift surface later. Different model family reading fresh catches a lot.",
    dateAdded: ADDED,
  },
  {
    id: "318335be-e2a3-4003-a217-2efa6bc83b3d",
    ownerEmail: OWNER,
    title: "Claude te consigue nuevos clientes — Soy Enrique Rocha (reel)",
    url: "https://www.facebook.com/reel/26877964915218310",
    summary: "Segundo reel de Soy Enrique Rocha en la misma serie sobre usar Claude para conseguir clientes. Promueve un flujo automatizado de prospección con Claude que ayuda a freelancers/agencias a obtener leads. 2.4K reacciones, 832 comentarios.",
    category: "ai",
    subcategory: "tool",
    tags: ["claude", "prospeccion", "ventas", "enrique-rocha", "espanol"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
  {
    id: "b9460f43-ed2c-424a-b4fc-916c12a376ff",
    ownerEmail: OWNER,
    title: "localTv — Self-hosted live TV + sports streaming aggregator",
    url: "https://github.com/jobustamantedev/localTv",
    summary: "Web-based streaming platform that aggregates 100+ live TV channels and sports events (NBA, Copa Libertadores, etc.), accessible across devices on your local network. Clean browse UI with search, live status indicators, and stream badges. Includes a RESTful API with Swagger docs and an admin panel for channel management. Docker support; works on Smart TVs and other LAN devices. 70 stars, MIT.",
    category: "bookmarks",
    subcategory: "stream",
    tags: ["streaming", "live-tv", "sports", "self-hosted", "docker"],
    source: "facebook",
    read: false,
    dateAdded: ADDED,
  },
];

async function main() {
  for (const item of items) {
    const existing = await prisma.item.findUnique({ where: { id: item.id } });
    if (existing) {
      console.log(`SKIP (already exists): ${item.title}`);
      continue;
    }
    await prisma.item.create({ data: item });
    console.log(`ADDED: ${item.title}`);
  }
  await prisma.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
