import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const EMAIL = "edwin.vega@gmail.com";
const NOW = new Date("2026-03-10T00:00:00Z");

const items = [
  // ── AI TOOLS / GITHUB ────────────────────────────────────────
  {
    id: "aa27f5e5-7554-4168-81e9-600c811b65df",
    title: "AI-Driven End-to-End Test Automation Process",
    url: "https://www.linkedin.com/posts/vikhar_ai-driven-end-to-end-test-automation-process-share-7433929359595339776-6iEF",
    summary: "A LinkedIn post describing a four-stage AI-powered QA pipeline that automates the full testing lifecycle: requirement intake via a Jira Issue Reader, BDD/Gherkin test case generation in Zephyr, AI code-generation of Selenium/Python scripts, and automated CI/CD execution with AI result analysis that files defect tickets back in Jira. Model Context Protocol (MCP) bridges handle API authentication and data standardization across stages. Community comments emphasize the importance of human review checkpoints, noting ~60% of test cases may fail across releases without proper validation gates.",
    category: "ai", subcategory: "tool",
    tags: ["test-automation", "ai-agents", "mcp", "qa", "devops"],
    source: "linkedin",
  },
  {
    id: "a16bce75-c2e3-4b4c-9cf8-eb391eb2deaa",
    title: "Agency Agents — Open-Source 51-Agent AI Agency for Claude Code",
    url: "https://www.facebook.com/share/1DKrmFLEtq/",
    summary: "Agency Agents is a fully open-source AI agency system built on Claude Code, featuring 51 specialized agents organized into departments like strategy, creative, engineering, and media. The project enables multi-agent collaboration where agents can delegate tasks to each other and operate as a coordinated team. It is positioned as a replacement for expensive human agencies, running entirely through Claude Code. Available on GitHub.",
    category: "ai", subcategory: "tool",
    tags: ["claude-code", "multi-agent", "open-source", "automation", "agency"],
    source: "facebook",
  },
  {
    id: "f5bd043c-66d0-433f-af7a-3c00c0353d5c",
    title: "Perplexity: The Operating System for Real Work",
    url: "https://www.facebook.com/share/1EeX4fsGYZ/",
    summary: "A post framing Perplexity AI not as a simple search tool but as a full operating system for real work, capable of searching the web, running code, reading files, and taking actions autonomously. It highlights Perplexity's ability to chain tasks together without human prompting between steps, making it competitive with traditional productivity software. The post positions Perplexity as a significant shift in how knowledge workers interact with AI.",
    category: "ai", subcategory: "news",
    tags: ["perplexity", "ai-productivity", "search", "agentic-ai"],
    source: "facebook",
  },
  {
    id: "d1a4e9f8-c6d8-4922-a31b-28a10b767ab2",
    title: "9 ChatGPT Prompts to Make Money",
    url: "https://www.facebook.com/share/14Y5tGokqzM/",
    summary: "A viral post sharing 9 specific ChatGPT prompts designed to help users generate income, covering areas like starting a side hustle, finding investment opportunities, writing sales copy, and identifying market gaps. Each prompt is structured to extract actionable financial and business advice from ChatGPT. The post targets people looking to use AI as a practical money-making tool.",
    category: "ai", subcategory: "prompt",
    tags: ["chatgpt", "prompts", "side-hustle", "money", "business"],
    source: "facebook",
  },
  {
    id: "fa2c2073-848c-4173-8a0b-b655b6b4fe8e",
    title: "Free AI Agents & Automations — Sabrina Ramonov",
    url: "https://agents.sabrina.dev/",
    summary: "A community-driven directory by Sabrina Ramonov offering free, searchable AI agent templates and workflow automations to help users streamline repetitive tasks. The platform supports multiple automation platforms and is filterable by category, with options to request or contribute new automations. Aimed at developers and non-technical users alike who want to get started building AI-powered workflows without starting from scratch.",
    category: "ai", subcategory: "tool",
    tags: ["ai-agents", "automation", "no-code", "workflows", "free"],
    source: "web",
  },
  {
    id: "5a838b13-f141-4f2d-bad9-8183d293ffa5",
    title: "Google Workspace CLI (gws) — Open-Source Command-Line Interface",
    url: "https://www.facebook.com/share/p/1D4ebFwWgn/",
    summary: "Google has open-sourced a command-line interface tool called gws that allows developers and power users to interact with Google Workspace (Gmail, Drive, Calendar, Docs) entirely from the terminal. The tool enables scripting, automation, and AI agent integration with Google's productivity suite without needing a browser. It positions Google Workspace as more developer-friendly and agent-compatible.",
    category: "ai", subcategory: "tool",
    tags: ["google-workspace", "cli", "open-source", "automation", "developer-tools"],
    source: "facebook",
  },
  {
    id: "7c82cb23-a44b-494a-b6a3-1a7bb6645d36",
    title: "7 Claude Prompts to Replace Canva for Design Work",
    url: "https://www.facebook.com/share/17MujbcyzE/",
    summary: "A post presenting 7 specific Claude prompts that can replicate common Canva design workflows, including generating social media post copy, designing layout descriptions, creating color palettes, and producing brand style guides. The framing positions Claude as capable of handling design thinking and content creation tasks that users typically rely on Canva for. Each prompt is actionable and formatted for direct use.",
    category: "ai", subcategory: "prompt",
    tags: ["claude", "design", "canva", "prompts", "content-creation"],
    source: "facebook",
  },
  {
    id: "320060ca-cc79-4d9e-8793-1460560ad3e7",
    title: "7 Claude Prompts to Grow a YouTube Channel from 0 to Monetization in 90 Days",
    url: "https://www.facebook.com/share/1Am7mj7QZb/",
    summary: "A post sharing 7 Claude prompts specifically designed to accelerate YouTube channel growth, covering niche selection, video script writing, SEO title optimization, thumbnail concept generation, community post ideas, analytics interpretation, and a 90-day content calendar. The system is framed as a complete YouTube growth engine powered by Claude. It targets creators who want to reach monetization thresholds faster using AI assistance.",
    category: "ai", subcategory: "prompt",
    tags: ["claude", "youtube", "content-creation", "prompts", "social-media"],
    source: "facebook",
  },
  {
    id: "280a78fb-8a08-4ee0-86fd-a3240aef2e54",
    title: "7 Claude Prompts to Replace Your Personal Trainer",
    url: "https://www.facebook.com/share/1AiYjjovwD/",
    summary: "A post outlining 7 Claude prompts that function as a full personal training system, including workout plan generation, nutrition advice, progress tracking, form correction guidance, motivation scripts, rest day protocols, and plateau-breaking strategies. The prompts are designed to be used together as an ongoing fitness coaching system entirely within Claude. It targets people looking to cut personal trainer costs while maintaining structured fitness guidance.",
    category: "ai", subcategory: "prompt",
    tags: ["claude", "fitness", "health", "prompts", "personal-trainer"],
    source: "facebook",
  },
  {
    id: "f8ad5f95-74fb-4852-9a8f-2cee29a0e121",
    title: "The 'Golden Response' Salary Negotiation Script",
    url: "https://www.facebook.com/share/1DQsZHtg3L/",
    summary: "A post sharing a specific salary negotiation script called the 'Golden Response,' designed to counter lowball offers without being confrontational. The technique involves expressing enthusiasm for the role, anchoring to a higher number with justification, and using silence strategically. The post explains the psychological principles behind why this script outperforms most standard negotiation advice and includes example dialogue.",
    category: "bookmarks", subcategory: "article",
    tags: ["salary-negotiation", "career", "communication", "productivity"],
    source: "facebook",
  },
  {
    id: "0c45042e-982b-4e37-bf3b-473b8ff81d9a",
    title: "Headroom — Open-Source LLM Context Optimization Layer",
    url: "https://www.facebook.com/share/1Jw3ZXGDJk/",
    summary: "Headroom is an open-source tool that sits between your application and LLM APIs to intelligently manage and optimize context windows, reducing token costs and improving response quality. It automatically summarizes, compresses, and prioritizes context based on relevance, making it especially useful for long-running agent sessions and chatbots with memory requirements. Supports multiple LLM providers.",
    category: "ai", subcategory: "tool",
    tags: ["llm", "context-window", "open-source", "optimization", "tokens"],
    source: "facebook",
  },
  {
    id: "89298184-cf19-4cf7-92ec-a31e2894aec7",
    title: "7 Claude Prompts to Replace Your Entire Productivity Stack",
    url: "https://www.facebook.com/61579900588732/posts/122132173796996686/",
    summary: "A viral post presenting 7 Claude prompts that collectively replace common productivity tools including email clients, note-taking apps, project managers, and writing assistants. Each prompt is designed as a workflow replacement covering email triage, meeting summaries, weekly planning, deep work sessions, knowledge capture, decision journaling, and end-of-day reviews. The post frames Claude as a complete operating system for personal productivity.",
    category: "ai", subcategory: "prompt",
    tags: ["claude", "productivity", "prompts", "workflow", "chatgpt"],
    source: "facebook",
  },
  {
    id: "5cbd389d-edcd-4b16-b551-e9803a91493e",
    title: "GitNexus — Open-Source Code Knowledge Graph for AI Agents",
    url: "https://www.facebook.com/share/17mNNTWhYN/",
    summary: "GitNexus is an open-source tool that builds a semantic knowledge graph from a codebase, enabling AI agents to understand code structure, relationships between files, and architectural patterns at a high level. It indexes repositories into a queryable graph that AI agents can traverse to answer questions about code without reading every file. Aims to make AI-assisted code navigation and refactoring significantly more accurate.",
    category: "ai", subcategory: "tool",
    tags: ["open-source", "code-analysis", "knowledge-graph", "ai-agents", "developer-tools"],
    source: "facebook",
  },
  {
    id: "3b6094f7-a39c-4767-a5b6-10c83e6a1476",
    title: "Claude Business Launch System — 7 Prompts from Idea to First Customer",
    url: "https://www.facebook.com/share/1DX9V7Gmr6/",
    summary: "A 7-prompt Claude system for launching a business in one week, covering idea-to-offer positioning, landing page copy generation, customer acquisition strategy, payment and delivery setup, launch week content planning, post-launch analysis, and a 30-day scale sprint. The author claims to have used this system to go from a business idea on Monday to a landing page, offer, and first paying customer by Friday. Each prompt builds on the previous in a structured sequence.",
    category: "ai", subcategory: "prompt",
    tags: ["claude", "business", "entrepreneurship", "prompts", "launch"],
    source: "facebook",
  },
  {
    id: "95ba575d-8269-4f36-9b64-f4077d5ef83d",
    title: "The Anatomy of a Claude Code Project — CLAUDE.md Structure Guide",
    url: "https://www.facebook.com/share/1DthMbtEaN/",
    summary: "A post explaining the correct structure for Claude Code projects, arguing that CLAUDE.md should function as a concise 'repo memory' rather than a knowledge dump. The guide outlines 5 key structural components: CLAUDE.md for purpose and rules, .claude/skills/ for reusable workflow modes, .claude/hooks/ for deterministic guardrails, docs/ for architecture references, and local CLAUDE.md files placed near risky modules. The post frames good project structure as the difference between Claude behaving like a chatbot versus a project-native engineer.",
    category: "ai", subcategory: "tutorial",
    tags: ["claude-code", "claude-md", "project-structure", "workflow", "best-practices"],
    source: "facebook",
  },
  {
    id: "7dd10206-7ad6-4460-949a-3b31b06edad6",
    title: "7 Claude Prompts for High-Stakes Business Decision Making",
    url: "https://www.facebook.com/share/1DQz5yQ3mL/",
    summary: "A post sharing 7 structured Claude prompts designed to bring Fortune 500-level rigor to business decisions. The prompts cover: classifying a decision by reversibility and stakes, expanding options by generating unconsidered alternatives, running a pre-mortem simulation, building a weighted criteria matrix, mapping hidden second-order costs, exposing unverified assumptions, and writing a structured decision log. Together they form a complete decision analysis framework that replaces gut-based choices with structured reasoning.",
    category: "ai", subcategory: "prompt",
    tags: ["claude", "decision-making", "business", "prompts", "strategy"],
    source: "facebook",
  },
  {
    id: "9dc6d606-ae06-43d4-9dd7-31b9c65bbdeb",
    title: "Free-TV/IPTV — Free Live TV Channels from 60+ Countries",
    url: "https://www.facebook.com/share/1DL3HEMrUs/",
    summary: "A GitHub project that compiles free over-the-air and internet TV channels from 60+ countries into a single M3U playlist compatible with any IPTV player. Sources include Plex, Pluto TV, Roku, Samsung TV Plus, and YouTube live channels, with an HD-first policy. Fully open-source and requires no subscription, making it a free alternative to paid IPTV services.",
    category: "bookmarks", subcategory: "reference",
    tags: ["iptv", "free-tv", "open-source", "streaming", "m3u"],
    source: "facebook",
  },
  {
    id: "43624703-2bd6-4324-af04-da072305e225",
    title: "Claude CoWork Setup Guide — 8 Steps to Configure It Correctly",
    url: "https://www.facebook.com/share/1bKh4TZZ9B/",
    summary: "An 8-step cheat sheet for setting up Claude CoWork (Anthropic's desktop app for professionals) as a structured thinking and execution environment. Key steps include selecting the right model (Opus with Extended Thinking), building a dedicated folder structure, writing CoWork instructions with context files and guardrails, installing plugins for clickable action buttons, and connecting tools like Slack, Google Drive, Notion, and Figma. The guide emphasizes that most users fail to unlock CoWork's power because they treat it like a chatbot rather than a configured workflow environment.",
    category: "ai", subcategory: "tutorial",
    tags: ["claude", "cowork", "setup", "workflow", "productivity"],
    source: "facebook",
  },
  {
    id: "25a253b8-b1df-4ea6-9430-91dd8bcd1faa",
    title: "Founders Kit — 500+ Resources for Building a Startup",
    url: "https://github.com/avinash201199/founders-kit",
    summary: "A curated collection of 500+ essential resources, tools, and playbooks to help founders build, launch, and scale startups. Organized into categories covering learning resources (books, essays, courses), fundraising guides, communities, growth tactics, and infrastructure tools. Addresses the pain point of scattered research by providing a single vetted starting point spanning every startup phase from ideation through scaling.",
    category: "bookmarks", subcategory: "reference",
    tags: ["startup", "founders", "entrepreneurship", "resources", "github"],
    source: "web",
  },
  {
    id: "ac9e5963-8704-40a4-8492-0070f08e9120",
    title: "Learn Claude Code — Build an AI Agent from Scratch",
    url: "https://github.com/shareAI-lab/learn-claude-code",
    summary: "An educational repository that deconstructs how AI coding agents work by progressively building one from scratch across 12 sequential sessions. Covers four phases: the basic agent loop, planning and subagents, persistence and task systems, and multi-agent coordination. Includes Python reference implementations, trilingual documentation (English, Chinese, Japanese), and interactive web visualizations. Ideal for developers who want to understand the mechanics behind tools like Claude Code.",
    category: "ai", subcategory: "tutorial",
    tags: ["claude-code", "ai-agents", "python", "tutorial", "open-source"],
    source: "web",
  },
  {
    id: "7c64b8c9-d241-4039-8f34-7d4a9baa60ac",
    title: "Awesome Agent Skills — 549+ Real-World AI Agent Skills",
    url: "https://github.com/VoltAgent/awesome-agent-skills",
    summary: "A curated directory of 549+ real-world AI agent skills created by leading engineering teams and the community, compatible with Claude Code, Cursor, Gemini CLI, and similar tools. Includes official Anthropic skills, framework-specific skills from Vercel, Netlify, and Cloudflare, and infrastructure skills from Stripe and HashiCorp. Emphasizes quality by featuring vetted skills published by actual development teams — an essential reference for extending AI agent capabilities.",
    category: "ai", subcategory: "tool",
    tags: ["claude-code", "agent-skills", "awesome-list", "ai-agents", "open-source"],
    source: "web",
  },
  {
    id: "9accf987-f938-447e-a88b-c764863cad7b",
    title: "Everything Claude Code — 16 Subagents, 65+ Skills, 40+ Commands",
    url: "https://github.com/affaan-m/everything-claude-code",
    summary: "A comprehensive plugin and configuration framework for Claude Code featuring 16 specialized subagents, 65+ domain-specific skills, and 40+ slash commands. Originated from an Anthropic hackathon winner and covers workflows for planning, architecture, code review, security scanning, and multi-language support. Includes a hooks architecture for session management and a continuous learning system that extracts reusable patterns from development sessions.",
    category: "ai", subcategory: "tool",
    tags: ["claude-code", "ai-agents", "developer-tools", "productivity", "open-source"],
    source: "web",
  },
  {
    id: "b63fa40a-ec3a-497f-b819-ade807e9a1ef",
    title: "AI Hedge Fund — Multi-Agent Investment Decision System",
    url: "https://github.com/virattt/ai-hedge-fund",
    summary: "A proof-of-concept educational project that uses 18 specialized AI agents to simulate investment decision-making, with personas modeled after Warren Buffett and Cathie Wood alongside analytical agents for valuation, sentiment, fundamentals, and technical analysis. Supports multiple LLM providers (OpenAI, Groq, Anthropic, DeepSeek, Ollama) and includes backtesting capability plus a web UI. Has amassed 47K+ GitHub stars and is explicitly for educational and research purposes only, not real trading.",
    category: "ai", subcategory: "tool",
    tags: ["ai-agents", "finance", "investing", "python", "open-source"],
    source: "web",
  },
  {
    id: "a0212b27-66d8-4227-8017-547b0b2a6bcd",
    title: "PinchTab — High-Performance Browser Automation for AI Agents",
    url: "https://github.com/pinchtab/pinchtab",
    summary: "A lightweight Go binary (12MB) that acts as an HTTP server enabling AI agents to control Chrome browsers programmatically, with support for multiple isolated Chrome instances and independent browser profiles. Notably token-efficient, extracting ~800 tokens per page versus thousands for screenshot-based approaches, significantly reducing LLM API costs. Includes a web dashboard, MCP/SMCP plugin integration, and ARM64 optimization for Raspberry Pi.",
    category: "ai", subcategory: "tool",
    tags: ["browser-automation", "ai-agents", "mcp", "go", "open-source"],
    source: "web",
  },
  {
    id: "a31d51aa-fd4d-4db5-9540-d0531394abc1",
    title: "The Complete Guide to Building Skills for Claude — Anthropic PDF",
    url: "https://resources.anthropic.com/hubfs/The-Complete-Guide-to-Building-Skill-for-Claude.pdf",
    summary: "An official Anthropic PDF guide covering everything needed to build, test, and distribute Claude skills — reusable instruction packages that teach Claude specific workflows without repeating context each conversation. Explains the three-level progressive disclosure architecture (YAML frontmatter, SKILL.md body, linked files) that minimizes token usage while maintaining specialized behavior. Includes chapters on planning and design, testing and iteration, distribution, patterns, and troubleshooting — promises a working skill in 15–30 minutes.",
    category: "ai", subcategory: "tutorial",
    tags: ["claude", "claude-code", "agent-skills", "anthropic", "tutorial"],
    source: "web",
  },
  {
    id: "14318345-9844-441e-87ae-c13074e33bdf",
    title: "10 Claude Code Plugins in 100 Seconds — YouTube Short",
    url: "https://youtube.com/shorts/_G3gTYm-e9E?si=8zqnPzhVIKh141sH",
    summary: "A fast-paced YouTube Short showcasing 10 Claude Code plugins (agent skills) in 100 seconds, giving developers a rapid visual overview of what's available in the Claude Code ecosystem. A useful discovery format for anyone wanting a quick survey of real-world Claude Code extensions without reading through long documentation. Part of the growing content ecosystem around Claude Code tooling and customization.",
    category: "ai", subcategory: "tutorial",
    tags: ["claude-code", "agent-skills", "youtube", "plugins", "tutorial"],
    source: "youtube",
  },
  {
    id: "450c527c-a2f2-4d77-ac18-02d3e03d6853",
    title: "Browser Use — Make Websites Accessible for AI Agents",
    url: "https://github.com/browser-use/browser-use",
    summary: "An open-source Python library with 80K+ GitHub stars that lets AI agents interact with websites through natural language task descriptions, powered by Playwright and compatible with OpenAI, Anthropic, Google Gemini, and other LLMs. Agents can fill forms, scrape data, complete multi-step tasks, and handle authentication without brittle CSS selectors or XPath. Integrates directly with coding agents like Claude Code and Cursor, and offers a cloud service with stealth browsing and proxy rotation for production deployments.",
    category: "ai", subcategory: "tool",
    tags: ["browser-automation", "ai-agents", "python", "playwright", "open-source"],
    source: "web",
  },
  {
    id: "69de6a15-7b41-403f-9f8d-bd5f99be2a7b",
    title: "Tour Aventura La Virgen — Day Trip to Waterfall & Kart Cross in Costa Rica",
    url: "https://vt.tiktok.com/ZSujehp8f/",
    summary: "A one-day adventure tour called 'Tour Aventura La Virgen' in Costa Rica, priced at ₡28,000 per person (~$55 USD). The tour includes transport from San Jose, Heredia, and Alajuela (departing 4:30am), breakfast, waterfall and natural pool access, and 3 laps on a kart cross circuit. Available dates in March–May 2026; reservation requires ₡10,000 deposit via WhatsApp 7259-2604.",
    category: "places", subcategory: "travel",
    tags: ["costa-rica", "adventure", "waterfall", "day-trip", "kart"],
    source: "tiktok",
  },
];

async function main() {
  console.log(`Inserting ${items.length} items for ${EMAIL}...`);

  for (const item of items) {
    await prisma.item.upsert({
      where: { id: item.id },
      update: {},
      create: {
        id: item.id,
        ownerEmail: EMAIL,
        title: item.title,
        url: item.url,
        summary: item.summary,
        category: item.category,
        subcategory: item.subcategory,
        tags: item.tags,
        source: item.source,
        read: false,
        dateAdded: NOW,
      },
    });
    console.log(`  ✓ ${item.title}`);
  }

  console.log("\nDone.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
